const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { once } = require('node:events');

test('HTTP flow serves UI, completes, imports atomically and survives restart', async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'career-quest-test-'));
  const source = path.join(__dirname, '..');
  for (const name of ['server.js', 'demo.json', 'lib', 'public']) fs.cpSync(path.join(source, name), path.join(root, name), { recursive: true });
  const modulePath = path.join(root, 'server.js');
  let server;
  let hrPassword;
  let hrCookie;
  const start = async () => {
    delete require.cache[require.resolve(modulePath)];
    const app = require(modulePath).createApp({ storage: path.join(root, 'private') });
    server = app.server;
    hrPassword ||= app.bootstrapPassword;
    server.listen(0, '127.0.0.1');
    await once(server, 'listening');
    const address = `http://127.0.0.1:${server.address().port}`;
    const login = await fetch(address + '/api/login', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:'hr',password:hrPassword})});
    assert.equal(login.status,200); hrCookie=login.headers.get('set-cookie').split(';')[0];
    return address;
  };
  const stop = () => new Promise((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
  try {
    let base = await start();
    const post = (route, body) => fetch(base + route, { method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: hrCookie }, body: JSON.stringify(body) });
    for (const asset of ['/', '/app.js', '/style.css']) assert.equal((await fetch(base + asset)).status, 200);
    assert.equal((await fetch(base + '/api/state')).status,401);
    const credentials=await (await post('/api/access',{employee_id:'demo-1'})).json();
    const login=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(credentials)});
    const employeeCookie=login.headers.get('set-cookie').split(';')[0];
    const own=await (await fetch(base+'/api/state',{headers:{Cookie:employeeCookie}})).json();
    assert.equal(own.employees.length,1); assert.equal(own.employees[0].id,'demo-1'); assert.equal(own.hr,undefined);
    const forbidden=async (route,body) => fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',Cookie:employeeCookie},body:JSON.stringify(body)});
    assert.equal((await forbidden('/api/complete',{employee_id:'demo-2',activity_id:'sql-lab'})).status,403);
    assert.equal((await forbidden('/api/import',{})).status,403);
    assert.equal((await forbidden('/api/access',{employee_id:'demo-2'})).status,403);
    assert.equal((await forbidden('/api/reset',{})).status,403);
    let state = await (await fetch(base + '/api/state', {headers:{Cookie:hrCookie}})).json();
    assert.equal(state.employees.length, 3);
    assert.equal((await post('/api/complete', { employee_id: 'demo-1', activity_id: 'python-lab' })).status, 200);
    assert.equal((await post('/api/complete', { employee_id: 'demo-1', activity_id: 'python-lab' })).status, 400);
    assert.equal((await post('/api/import', { employees: [] })).status, 400);
    const brokenSchedule = JSON.parse(fs.readFileSync(path.join(root, 'demo.json'), 'utf8'));
    brokenSchedule.activities[0].format = 'offline';
    assert.equal((await post('/api/import', brokenSchedule)).status, 400);
    const stillValid = await (await fetch(base + '/api/state', { headers: { Cookie: hrCookie } })).json();
    assert.equal(stillValid.employees[0].skills.python, 3);
    await stop();
    base = await start();
    state = await (await fetch(base + '/api/state', {headers:{Cookie:hrCookie}})).json();
    assert.equal(state.employees[0].skills.python, 3);
    assert.equal(state.employees[0].history.length, 1);
    const imported = JSON.parse(fs.readFileSync(path.join(root, 'demo.json'), 'utf8'));
    imported.employees[0].name = 'Проверочный профиль';
    const preImportAccess = await (await post('/api/access', { employee_id: 'demo-1' })).json();
    const preImportLogin = await fetch(base + '/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(preImportAccess) });
    const preImportCookie = preImportLogin.headers.get('set-cookie').split(';')[0];
    assert.equal((await fetch(base + '/api/state', { headers: { Cookie: preImportCookie } })).status, 200);
    assert.equal((await post('/api/import', imported)).status, 200);
    assert.equal((await fetch(base + '/api/state', { headers: { Cookie: preImportCookie } })).status, 401);
    state = await (await fetch(base + '/api/state', {headers:{Cookie:hrCookie}})).json();
    assert.equal(state.demo, false);
    assert.equal(state.employees[0].name, 'Проверочный профиль');
    assert.equal((await post('/api/reset', {})).status, 200);
    state = await (await fetch(base + '/api/state', {headers:{Cookie:hrCookie}})).json();
    assert.equal(state.demo, true);
    assert.equal(state.employees[0].history.length, 0);
    const rotatedAccess = await (await post('/api/access', { employee_id: 'demo-1' })).json();
    const renewedLogin = await fetch(base + '/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(rotatedAccess) });
    const rotatedCookie = renewedLogin.headers.get('set-cookie').split(';')[0];
    assert.equal((await post('/api/access', { employee_id: 'demo-1' })).status, 200);
    assert.equal((await fetch(base + '/api/state', { headers: { Cookie: rotatedCookie } })).status, 401);
    assert.equal((await fetch(base + '/api/reset', { method: 'POST', headers: { 'Content-Type': 'application/json', Cookie: hrCookie, Origin: 'https://untrusted.example' }, body: '{}' })).status, 403);
  } finally {
    if (server?.listening) await stop();
    // mkdtemp creates this exact isolated directory under the OS temp folder.
    if (path.dirname(root) === os.tmpdir() && path.basename(root).startsWith('career-quest-test-')) fs.rmSync(root, { recursive: true, force: true });
  }
});
